config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  resources :orders
  resources :track_orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	enum service_type: { 'Speed Post': 'speed post', 'Regular': 'regular'}
	enum payment_mode: { 'COD': 'cod', 'Prepaid': 'prepaid' }
	enum status: { 'Sent': 'sent', 'In Transit': 'in transit', 'Delivered': 'delivered'}
  validates :sender_full_name, :sender_email_address, :sender_address, :sender_phone_number, :sender_pin_code, :receiver_full_name, :receiver_email_address, :receiver_address, :receiver_phone_number, :receiver_pin_code, :parcel_weight, :service_type, :service_cost, :payment_mode, :status,  :presence => true
  before_save :generate_tracking_id

	private
	
	def generate_tracking_id
	  begin
	    self.tracking_id = 'CS' + SecureRandom.random_number(1_000_000).to_s
	  end while Order.where(id: self.id).exists?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        OrderMailer.sender_courier_email(@order).deliver_now!
        OrderMailer.receiver_courier_email(@order).deliver_now!
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:sender_full_name, :sender_address, :sender_phone_number, :sender_pin_code, :receiver_full_name, :receiver_address, :receiver_phone_number, :receiver_pin_code, :parcel_weight, :service_type, :service_cost, :payment_mode, :status, :tracking_id, :sender_email_address, :receiver_email_address)
    end
end

app/controllers/track_orders_controller.rb
class TrackOrdersController < ApplicationController
  def index
  end

  def create
    @order = Order.find_by_tracking_id(params[:tracking_id])
    respond_to do |format|
      format.js { }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/track_orders_helper.rb
module TrackOrdersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Courier Service", "/", class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/track_orders">Track Order</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>CourierService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="col-md-12">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :sender_full_name %>
    <%= form.text_field :sender_full_name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sender_email_address%>
    <%= form.email_field :sender_email_address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sender_address %>
    <%= form.text_area :sender_address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sender_phone_number %>
    <%= form.text_field :sender_phone_number, class: 'form-control', maxlength: 10, minlength: 10, required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sender_pin_code %>
    <%= form.number_field :sender_pin_code, class: 'form-control', maxlength: 6, minlength: 4, required: true   %>
  </div>

  <div class="form-group">
    <%= form.label :receiver_full_name %>
    <%= form.text_field :receiver_full_name, class: 'form-control', required: true  %>
  </div>

  <div class="form-group">
    <%= form.label :receiver_email_address%>
    <%= form.email_field :receiver_email_address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :receiver_address %>
    <%= form.text_area :receiver_address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :receiver_phone_number %>
    <%= form.text_field :receiver_phone_number, class: 'form-control', maxlength: 10, minlength: 10, required: true  %>
  </div>

  <div class="form-group">
    <%= form.label :receiver_pin_code %>
    <%= form.number_field :receiver_pin_code, class: 'form-control', maxlength: 6, minlength: 4, required: true  %>
  </div>

  <div class="form-group">
    <%= form.label :parcel_weight, 'Parcel Weight(in gms)' %>
    <%= form.text_field :parcel_weight, class: 'form-control', required: true  %>
  </div>

  <div class="form-group">
    <%= form.label :service_type %>
    <%= form.select :service_type, options_for_select(Order.service_types.map {|key, value| [key.titleize, Order.service_types.key(value)]}), {prompt: 'Select Service Type'},class: 'form-control', required: true %>

  </div>

  <div class="form-group">
    <%= form.label :service_cost, 'Service Cost(in INR)' %>
    <%= form.text_field :service_cost, class: 'form-control', required: true  %>
  </div>

  <div class="form-group">
    <%= form.label :payment_mode %>
    <%= form.select :payment_mode, options_for_select(Order.payment_modes.map {|key, value| [key.titleize, Order.payment_modes.key(value)]}), {prompt: 'Select Payment Mode'},class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Order.statuses.map {|key, value| [key.titleize, Order.statuses.key(value)]}), {prompt: 'Select Status'},class: 'form-control', required: true %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="width_30">
	<h1>Editing Order</h1>

	<%= render 'form', order: @order %>

	<%= link_to 'Show', @order %> |
	<%= link_to 'Back', orders_path %>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Sender full name</th>
      <th>Sender Email Address</th>
      <th>Sender address</th>
      <th>Sender phone number</th>
      <th>Sender pin code</th>
      <th>Receiver full name</th>
      <th>Receiver Email Address</th>
      <th>Receiver address</th>
      <th>Receiver phone number</th>
      <th>Receiver pin code</th>
      <th>Parcel weight</th>
      <th>Service type</th>
      <th>Service cost</th>
      <th>Payment mode</th>
      <th>Status</th>
      <th>Tracking ID</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.sender_full_name %></td>
        <td><%= order.sender_email_address %></td>
        <td><%= order.sender_address %></td>
        <td><%= order.sender_phone_number %></td>
        <td><%= order.sender_pin_code %></td>
        <td><%= order.receiver_full_name %></td>
        <td><%= order.receiver_email_address %></td>
        <td><%= order.receiver_address %></td>
        <td><%= order.receiver_phone_number %></td>
        <td><%= order.receiver_pin_code %></td>
        <td><%= order.parcel_weight %></td>
        <td><%= order.service_type %></td>
        <td><%= order.service_cost %></td>
        <td><%= order.payment_mode %></td>
        <td><%= order.status %></td>
        <td><%= order.tracking_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="width_30">
	<h1>New Order</h1>
	<%= render 'form', order: @order %>
	<%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender full name:</strong>
  <%= @order.sender_full_name %>
</p>

<p>
  <strong>Sender email address:</strong>
  <%= @order.sender_email_address %>
</p>

<p>
  <strong>Sender address:</strong>
  <%= @order.sender_address %>
</p>

<p>
  <strong>Sender phone number:</strong>
  <%= @order.sender_phone_number %>
</p>

<p>
  <strong>Sender pin code:</strong>
  <%= @order.sender_pin_code %>
</p>

<p>
  <strong>Receiver full name:</strong>
  <%= @order.receiver_full_name %>
</p>

<p>
  <strong>Receiver email address:</strong>
  <%= @order.receiver_email_address %>
</p>


<p>
  <strong>Receiver address:</strong>
  <%= @order.receiver_address %>
</p>

<p>
  <strong>Receiver phone number:</strong>
  <%= @order.receiver_phone_number %>
</p>

<p>
  <strong>Receiver pin code:</strong>
  <%= @order.receiver_pin_code %>
</p>

<p>
  <strong>Parcel weight:</strong>
  <%= @order.parcel_weight %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @order.service_type %>
</p>

<p>
  <strong>Service cost:</strong>
  <%= @order.service_cost %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @order.payment_mode %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/track_orders/_order_info.html.erb
<% unless @order.blank? %>
  <h4>Result:</h4>
  <h5>Tracking ID: <%= @order.tracking_id %><h5>
  <h5>Status: <%= @order.status %></h5>
<% else %>
  <p>No records found.</p>
<% end %>

app/views/track_orders/create.js.erb
$("#result_container").html("<%= escape_javascript(render partial: 'order_info') %>");

app/views/track_orders/index.html.erb
<div class="width_30">
  <h3>Track your courier here</h3>
  <%= form_tag track_orders_path, remote: true do %>
    <div class="form-group" style="display: flex;">
      <%= text_field_tag :tracking_id, "", class: 'form-control', required: true, placeholder: 'Type tracking id here' %>
      <%= submit_tag('Search', class: 'btn btn-primary', id: 'search_order')%>
    </div>
  <% end %>
  <br/>

  <div id="result_container">
  </div>
</div>